#!/bin/sh

set -eu

export PRISMA_TELEMETRY_INFORMATION='ecosystem-tests platforms vercel-with-nextjs-caching build'

export VERCEL_PROJECT_ID="$VERCEL_WITH_NEXTJS_CACHING_PROJECT_ID"

pnpm install

export VERCEL_ORG_ID="$VERCEL_ORG_ID"
echo "VERCEL_ORG_ID: $VERCEL_ORG_ID"
echo "VERCEL_PROJECT_ID: $VERCEL_PROJECT_ID"
echo "PRISMA_CLIENT_ENGINE_TYPE: $PRISMA_CLIENT_ENGINE_TYPE"
