// Generated by Wrangler on Wed Mar 06 2024 14:45:29 GMT+0100 (Central European Standard Time)
// by running `wrangler types`

interface Env {
	DRIVER_ADAPTERS_NEON_CFPAGES_REMIX_DATABASE_URL: string;
}
